apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'flyctl deploy'
description: 'flyctl deploy'

inputs:
  image-name:
    description: 'image name'
    required: true
  region:
    description: 'region to deploy to'
    required: true
  fly-api-token-property:
    description: 'Fly API token property'
    required: true
  
runs:
  using: composite
  steps:
    - id: flyctl-deploy
      name: Deploy to a specific Fly region
      uses: docker://darinpope/flyctl:0.1.129
      shell: sh
      env:
        FLY_API_TOKEN: ${{ secrets.${{ inputs.fly-api-token-property }} }}
        NO_COLOR: "1"
      run: |
        flyctl auth docker
        flyctl regions set ${{ inputs.region }}
        flyctl deploy --image ${{ inputs.image-name }} --now